/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define BIT(n) (1u << (n))
#define REG32(addr) (*(volatile uint32_t *)(addr))

#define SCB_CPACR REG32(0xE000ED88u)

#define SYST_CSR REG32(0xE000E010u)
#define SYST_RVR REG32(0xE000E014u)
#define SYST_CVR REG32(0xE000E018u)

#define FLASH_ACR REG32(0x40023C00u)

#define RCC_BASE 0x40023800u
#define RCC_CR REG32(RCC_BASE + 0x00u)
#define RCC_PLLCFGR REG32(RCC_BASE + 0x04u)
#define RCC_CFGR REG32(RCC_BASE + 0x08u)
#define RCC_AHB1ENR REG32(RCC_BASE + 0x30u)
#define RCC_APB1RSTR REG32(RCC_BASE + 0x20u)
#define RCC_APB1ENR REG32(RCC_BASE + 0x40u)

#define GPIOA_BASE 0x40020000u
#define GPIOB_BASE 0x40020400u
#define GPIOC_BASE 0x40020800u

#define GPIO_MODER(base) REG32((base) + 0x00u)
#define GPIO_OTYPER(base) REG32((base) + 0x04u)
#define GPIO_OSPEEDR(base) REG32((base) + 0x08u)
#define GPIO_PUPDR(base) REG32((base) + 0x0Cu)
#define GPIO_BSRR(base) REG32((base) + 0x18u)
#define GPIO_AFRL(base) REG32((base) + 0x20u)
#define GPIO_AFRH(base) REG32((base) + 0x24u)

#define USART2_BASE 0x40004400u
#define USART2_SR REG32(USART2_BASE + 0x00u)
#define USART2_DR REG32(USART2_BASE + 0x04u)
#define USART2_BRR REG32(USART2_BASE + 0x08u)
#define USART2_CR1 REG32(USART2_BASE + 0x0Cu)

#define I2C1_BASE 0x40005400u
#define I2C1_CR1 REG32(I2C1_BASE + 0x00u)
#define I2C1_CR2 REG32(I2C1_BASE + 0x04u)
#define I2C1_DR REG32(I2C1_BASE + 0x10u)
#define I2C1_SR1 REG32(I2C1_BASE + 0x14u)
#define I2C1_SR2 REG32(I2C1_BASE + 0x18u)
#define I2C1_CCR REG32(I2C1_BASE + 0x1Cu)
#define I2C1_TRISE REG32(I2C1_BASE + 0x20u)

#define ICM20948_WHO_AM_I 0x00u
#define ICM20948_REG_BANK_SEL 0x7Fu
#define ICM20948_EXPECTED_WHOAMI 0xEAu

static void led_on(void) { GPIO_BSRR(GPIOC_BASE) = BIT(13 + 16); }
static void led_off(void) { GPIO_BSRR(GPIOC_BASE) = BIT(13); }

void SystemInit(void)
{
    SCB_CPACR |= (0xFu << 20);
    __asm volatile("dsb");
    __asm volatile("isb");

    RCC_CR |= BIT(0);
    while ((RCC_CR & BIT(1)) == 0) {
    }

    FLASH_ACR = (FLASH_ACR & ~0x7u) | 0x2u | BIT(8) | BIT(9) | BIT(10);
    RCC_CFGR = (RCC_CFGR & ~((0xFu << 4) | (0x7u << 10) | (0x7u << 13))) | (4u << 10);
    RCC_PLLCFGR = 16u | (336u << 6) | (1u << 16) | (7u << 24);
    RCC_CR |= BIT(24);
    while ((RCC_CR & BIT(25)) == 0) {
    }

    RCC_CFGR = (RCC_CFGR & ~0x3u) | 0x2u;
    while ((RCC_CFGR & 0xCu) != 0x8u) {
    }
}

static void systick_init(void)
{
    SYST_RVR = 84000u - 1u;
    SYST_CVR = 0;
    SYST_CSR = BIT(0) | BIT(2);
}

static void delay_ms(uint32_t ms)
{
    while (ms-- != 0) {
        SYST_CVR = 0;
        while ((SYST_CSR & BIT(16)) == 0) {
        }
    }
}

static void gpio_init(void)
{
    RCC_AHB1ENR |= BIT(0) | BIT(1) | BIT(2);

    GPIO_MODER(GPIOC_BASE) = (GPIO_MODER(GPIOC_BASE) & ~(3u << 26)) | (1u << 26);
    led_off();

    GPIO_MODER(GPIOA_BASE) = (GPIO_MODER(GPIOA_BASE) & ~((3u << 4) | (3u << 6))) | (2u << 4) | (2u << 6);
    GPIO_OSPEEDR(GPIOA_BASE) |= (3u << 4) | (3u << 6);
    GPIO_PUPDR(GPIOA_BASE) = (GPIO_PUPDR(GPIOA_BASE) & ~((3u << 4) | (3u << 6))) | (1u << 4) | (1u << 6);
    GPIO_AFRL(GPIOA_BASE) = (GPIO_AFRL(GPIOA_BASE) & ~((0xFu << 8) | (0xFu << 12))) | (7u << 8) | (7u << 12);

    GPIO_MODER(GPIOB_BASE) = (GPIO_MODER(GPIOB_BASE) & ~((3u << 16) | (3u << 18))) | (2u << 16) | (2u << 18);
    GPIO_OTYPER(GPIOB_BASE) |= BIT(8) | BIT(9);
    GPIO_OSPEEDR(GPIOB_BASE) |= (3u << 16) | (3u << 18);
    GPIO_PUPDR(GPIOB_BASE) = (GPIO_PUPDR(GPIOB_BASE) & ~((3u << 16) | (3u << 18))) | (1u << 16) | (1u << 18);
    GPIO_AFRH(GPIOB_BASE) = (GPIO_AFRH(GPIOB_BASE) & ~((0xFu << 0) | (0xFu << 4))) | (4u << 0) | (4u << 4);
}

static void uart2_init(void)
{
    RCC_APB1ENR |= BIT(17);
    USART2_BRR = 365u;
    USART2_CR1 = BIT(13) | BIT(3) | BIT(2);
}

static void uart2_putc(char c)
{
    if (c == '\n') {
        uart2_putc('\r');
    }
    while ((USART2_SR & BIT(7)) == 0) {
    }
    USART2_DR = (uint8_t)c;
}

static void uart2_puts(const char *s)
{
    while (*s != '\0') {
        uart2_putc(*s++);
    }
}

static void uart2_hex8(uint8_t value)
{
    static const char hex[] = "0123456789ABCDEF";
    uart2_putc(hex[value >> 4]);
    uart2_putc(hex[value & 0x0Fu]);
}

static void i2c1_init(void)
{
    RCC_APB1ENR |= BIT(21);
    RCC_APB1RSTR |= BIT(21);
    RCC_APB1RSTR &= ~BIT(21);

    I2C1_CR1 = 0;
    I2C1_CR2 = 42u;
    I2C1_CCR = 210u;
    I2C1_TRISE = 43u;
    I2C1_CR1 = BIT(10) | BIT(0);
}

// ponytail: blocking I2C is enough for bench bring-up; use interrupts/DMA when streaming real pose samples.
static void i2c_clear_addr(void)
{
    (void)I2C1_SR1;
    (void)I2C1_SR2;
}

static void i2c_fail_stop(void)
{
    I2C1_CR1 |= BIT(9);
    I2C1_SR1 &= ~(BIT(8) | BIT(9) | BIT(10) | BIT(11) | BIT(14));
}

static int i2c_wait_not_busy(void)
{
    for (uint32_t t = 500000u; t != 0; --t) {
        if ((I2C1_SR2 & BIT(1)) == 0) {
            return 0;
        }
    }
    return -1;
}

static int i2c_wait_sr1(uint32_t mask)
{
    for (uint32_t t = 500000u; t != 0; --t) {
        uint32_t sr1 = I2C1_SR1;
        if ((sr1 & (BIT(8) | BIT(9) | BIT(10) | BIT(11) | BIT(14))) != 0) {
            return -1;
        }
        if ((sr1 & mask) != 0) {
            return 0;
        }
    }
    return -1;
}

static int i2c_start_addr(uint8_t addr_rw)
{
    I2C1_CR1 |= BIT(8);
    if (i2c_wait_sr1(BIT(0)) != 0) {
        return -1;
    }
    I2C1_DR = addr_rw;
    if (i2c_wait_sr1(BIT(1)) != 0) {
        i2c_fail_stop();
        return -1;
    }
    return 0;
}

static int i2c_write_reg(uint8_t addr, uint8_t reg, uint8_t value)
{
    if (i2c_wait_not_busy() != 0 || i2c_start_addr((uint8_t)(addr << 1)) != 0) {
        return -1;
    }
    i2c_clear_addr();
    if (i2c_wait_sr1(BIT(7)) != 0) {
        i2c_fail_stop();
        return -1;
    }
    I2C1_DR = reg;
    if (i2c_wait_sr1(BIT(7)) != 0) {
        i2c_fail_stop();
        return -1;
    }
    I2C1_DR = value;
    if (i2c_wait_sr1(BIT(2)) != 0) {
        i2c_fail_stop();
        return -1;
    }
    I2C1_CR1 |= BIT(9);
    return 0;
}

static int i2c_read_reg(uint8_t addr, uint8_t reg, uint8_t *value)
{
    if (i2c_wait_not_busy() != 0 || i2c_start_addr((uint8_t)(addr << 1)) != 0) {
        return -1;
    }
    i2c_clear_addr();
    if (i2c_wait_sr1(BIT(7)) != 0) {
        i2c_fail_stop();
        return -1;
    }
    I2C1_DR = reg;
    if (i2c_wait_sr1(BIT(2)) != 0 || i2c_start_addr((uint8_t)((addr << 1) | 1u)) != 0) {
        i2c_fail_stop();
        return -1;
    }

    I2C1_CR1 &= ~BIT(10);
    i2c_clear_addr();
    I2C1_CR1 |= BIT(9);

    if (i2c_wait_sr1(BIT(6)) != 0) {
        I2C1_CR1 |= BIT(10);
        i2c_fail_stop();
        return -1;
    }
    *value = (uint8_t)I2C1_DR;
    I2C1_CR1 |= BIT(10);
    return 0;
}

static int icm20948_whoami(uint8_t addr, uint8_t *whoami)
{
    if (i2c_write_reg(addr, ICM20948_REG_BANK_SEL, 0x00u) != 0) {
        return -1;
    }
    delay_ms(2);
    return i2c_read_reg(addr, ICM20948_WHO_AM_I, whoami);
}

static void blink_forever(uint32_t on_ms, uint32_t off_ms)
{
    for (;;) {
        led_on();
        delay_ms(on_ms);
        led_off();
        delay_ms(off_ms);
    }
}

int main(void)
{
    uint8_t addr = 0x68u;
    uint8_t whoami = 0;

    systick_init();
    gpio_init();
    uart2_init();
    i2c1_init();

    uart2_puts("\njjkVR STM32F411 IMU bring-up\n");
    uart2_puts("I2C1 PB8=SCL PB9=SDA, USART2 PA2=TX PA3=RX, LED=PC13\n");

    if (icm20948_whoami(addr, &whoami) != 0) {
        addr = 0x69u;
        whoami = 0;
        (void)icm20948_whoami(addr, &whoami);
    }

    uart2_puts("ICM20948 addr=0x");
    uart2_hex8(addr);
    uart2_puts(" WHO_AM_I=0x");
    uart2_hex8(whoami);
    uart2_puts("\n");

    if (whoami == ICM20948_EXPECTED_WHOAMI) {
        uart2_puts("IMU OK\n");
        blink_forever(50, 950);
    }

    uart2_puts("IMU not found; expected WHO_AM_I=0xEA\n");
    blink_forever(100, 100);
}
